# 代替原db.properties文件
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: password
    password: 963852741..
  redis:
    host: localhost
    port: 6379
    database: 1
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp
#      suffix: .jsp

server:
  servlet:
    context-path: /DormitorySystem
# 配置mybatis的mapper扫描路径和别名管理器，注意：原项目中的mapper文件是在dao文件夹下，当前的配置不一定正确
# 同时还应该在启动类中添加@MapperScan注解或者在接口开发时直接添加@Mapper，才能扫描指定的包（暂时还未添加）
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-location: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.gdut.dormitory_system.entity # 这里好像要写实体包的位置


logging:
  level:
    com.gdut.dormitory_system.dao: debug

dormitory-system:
  ticket-expired-seconds: 3600

#spring.resources.static-locations=/static/